# Projeto 1 - Ciência dos Dados

Nome: Fernando Giuseppe Avila Beltramo

## Pergunta (s) a ser respondida

Q1: Países que se juntam ao Digital 9 tiveram aumento notável em usuários da internet?

## Explicação da hipótese e mecanismo

O Digital 9 (Digital 5 até 2018) é uma rede colaborativa de E-Governments com o objetivo comum de melhorar a vida dos cidadãos através do emprego de tecnologia digital. Pode-se inferir que países membros deste grupo possuam níveis de acessibilidade à Internet elevados.

>Mais sobre o Digital 9: https://www.digital.govt.nz/digital-government/international-partnerships/the-digital-9/

>Mais sobre o Digital 5: https://www.digital.govt.nz/digital-government/international-partnerships/the-digital-9/d5-summit/

## Bases de dados usadas

Pessoas usando a Internet (%):

>Site - https://data.worldbank.org/indicator/IT.NET.USER.ZS

>Excel - http://api.worldbank.org/v2/en/indicator/IT.NET.USER.ZS?downloadformat=excel

## Análise de dados

Insira abaixo uma análise de dados tratada para ter maior clareza. 

Lembre-se de que, além deste arquivo principal, você precisa entregar um ou mais *notebooks* mais brutos com todas as tentativas que fez e que não deram certo .

**Não inclua dados ou gráficos sem motivação nem interpretação** - sempre que fizer uma análise, plot ou tablea, diga qual sua intenção. Logo após a apresentação diga qual conclusão específica ou interpretação você tira daquela análise

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
digital_5 = ["Estonia", "Israel", "New Zealand", "United Kingdom", "Korea, Rep."]

In [3]:
internet_users_filename = "Individual_usign_internet.xls"
internet_users_raw = pd.read_excel(internet_users_filename, sheet_name="Data", skiprows=3)

In [4]:
internet_users_v1 = internet_users_raw.set_index("Country Name")
internet_users_v1.drop(["Country Code", "Indicator Name", "Indicator Code"], axis=1 , inplace=True)

In [38]:
internet_users_digital_5 = internet_users_v1.loc[digital_5[:]]
internet_users_digital_5.dropna(axis=1, how="all", inplace=True)
internet_users_digital_5.at["Estonia", "1991"] = ((internet_users_digital_5.at["Estonia", "1990"] + internet_users_digital_5.at["Estonia", "1992"]) / 2)
internet_users_digital_5.at["New Zealand", "1991"] = ((internet_users_digital_5.at["New Zealand", "1990"] + internet_users_digital_5.at["New Zealand", "1992"]) / 2)
internet_users_digital_5

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Name,,,,,,,,,,,,,,,,,,,,,
Estonia,0.000000,0.032742,0.065485,0.300711,1.159751,2.778968,3.525111,5.706277,10.796035,14.500897,...,70.58,72.50,74.10,76.500000,78.389926,80.004300,84.241528,87.237332,87.237332,88.102457
Israel,0.110774,0.214624,0.310579,0.398833,0.576966,0.930423,2.168368,4.399405,10.307070,13.436122,...,59.39,63.12,67.50,68.873878,70.800000,70.250312,75.017753,77.352090,79.653124,81.581184
New Zealand,0.000000,0.142971,0.285941,0.631215,3.168719,4.884241,8.041899,14.601524,31.636261,41.494483,...,72.03,79.70,80.46,81.230000,81.644470,82.780000,85.500000,88.222889,88.470186,90.811093
United Kingdom,0.087355,0.174231,0.260615,0.519762,1.036609,1.895168,4.123650,7.385399,13.669983,21.293638,...,78.39,83.56,85.00,85.379999,87.479998,89.844100,91.610000,92.000300,94.620000,94.620000
"Korea, Rep.",0.023265,0.046124,0.098404,0.249947,0.311359,0.819687,1.624237,3.600802,6.781815,23.552194,...,81.00,81.60,83.70,83.759120,84.070000,84.770000,87.556826,89.900000,92.843026,95.097149

In [19]:
internet_users_v2 = internet_users_v1.drop(internet_users_v1.iloc[:, 0:30], axis=1)

In [20]:
internet_users_v2.dropna(axis=0, how="all", inplace=True)
internet_users_v2.dropna(axis=1, how="all", inplace=True)

In [24]:
internet_users_v2

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
Country Name,,,,,,,,,,,,,,,,,,,,,
Aruba,0.000000,NaN,NaN,NaN,NaN,NaN,2.768383,NaN,NaN,4.506179,...,52.000000,58.000000,62.000000,69.000000,74.000000,78.900000,83.780000,88.661227,93.542454,97.170000
Afghanistan,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.840000,3.550000,4.000000,5.000000,5.454545,5.900000,7.000000,8.260000,10.595726,11.447688
Angola,0.000000,NaN,NaN,NaN,NaN,NaN,0.000776,0.005674,0.018454,0.071964,...,1.900000,2.300000,2.800000,3.100000,6.500000,8.900000,10.200000,12.400000,13.000000,14.339079
Albania,0.000000,NaN,NaN,NaN,NaN,0.011169,0.032197,0.048594,0.065027,0.081437,...,23.860000,41.200000,45.000000,49.000000,54.655959,57.200000,60.100000,63.252933,66.363445,71.847041
Andorra,0.000000,NaN,NaN,NaN,NaN,NaN,1.526601,3.050175,6.886209,7.635686,...,70.040000,78.530000,81.000000,81.000000,86.434425,94.000000,95.900000,96.910000,97.930637,98.871436
Arab World,0.000000,NaN,NaN,NaN,NaN,0.017674,0.039151,0.135567,0.270071,0.616816,...,18.495906,21.426349,24.775941,26.582764,30.178233,32.928038,36.457958,39.929358,42.679432,48.847621
United Arab Emirates,0.000000,NaN,NaN,NaN,NaN,0.102939,0.375394,3.295593,6.908303,14.942699,...,63.000000,64.000000,68.000000,78.000000,84.999991,88.000000,90.400000,90.500000,90.600007,94.819923
Argentina,0.000000,NaN,0.002993,0.029527,0.043706,0.086277,0.141955,0.280340,0.830767,3.284482,...,28.112623,34.000000,45.000000,51.000000,55.800000,59.900000,64.700000,68.043064,70.968981,75.809744
Armenia,0.000000,NaN,NaN,NaN,0.009117,0.052743,0.094573,0.111651,0.128659,0.970738,...,6.210000,15.300000,25.000000,32.000000,37.500000,41.900000,54.622806,59.102378,64.346030,69.718125
American Samoa,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Antigua and Barbuda,0.000000,NaN,NaN,NaN,NaN,2.200769,2.858450,3.480537,4.071716,5.300681,...,38.000000,42.000000,47.000000,52.000000,58.000000,63.400000,67.780000,70.000000,73.000000,76.000000
Australia,0.585095,1.097204,1.768765,1.974611,2.232101,2.759655,3.275250,16.369358,30.813239,40.783784,...,71.670000,74.250000,76.000000,79.487698,79.000000,83.453497,84.000000,84.560519,86.540000,86.544721
Austria,0.130369,0.259082,0.642818,0.765343,1.393423,1.890211,6.909162,9.533974,15.421219,23.044317,...,72.870000,73.450000,75.170000,78.739993,80.029994,80.618800,80.995825,83.940142,84.323331,87.935587
Azerbaijan,0.000000,NaN,NaN,NaN,0.001431,0.002056,0.006355,0.025188,0.037485,0.099229,...,17.080000,27.400000,46.000000,50.000000,54.200000,73.000001,75.000016,77.000000,78.200000,79.000000
Burundi,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000804,0.007979,0.015843,0.039204,...,0.810000,0.900000,1.000000,1.110000,1.220000,1.264218,1.380000,4.866224,5.173627,5.594671
Belgium,0.001007,0.020073,0.100041,0.199446,0.695995,0.991663,2.968412,4.938081,7.886623,13.772214,...,66.000000,70.000000,75.000000,81.609996,80.719991,82.170200,85.000000,85.052900,86.516500,87.679681
Benin,0.000000,NaN,NaN,NaN,NaN,NaN,0.001693,0.024649,0.047877,0.154907,...,1.850000,2.240000,3.130000,4.148323,4.500000,4.900000,6.000000,11.254988,11.994048,14.119012
Burkina Faso,0.000000,NaN,NaN,NaN,NaN,NaN,0.000961,0.018686,0.045423,0.061780,...,0.920000,1.130000,2.400000,3.000000,3.725035,9.100000,9.400000,11.387646,13.960000,15.876207
Bangladesh,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000751,0.003685,0.036170,...,2.500000,3.100000,3.700000,4.500000,5.000000,6.630000,13.900000,14.400000,18.020000,18.020000
Bulgaria,0.000000,NaN,NaN,0.002339,0.019527,0.119666,0.725251,1.219813,1.844965,2.908154,...,39.670000,45.000000,46.230000,47.979993,51.899988,53.061500,55.490000,56.656300,59.825548,63.410101
Bahrain,0.000000,NaN,NaN,NaN,NaN,0.346206,0.843254,1.646299,3.218202,4.720358,...,51.950000,53.000000,55.000000,76.999966,88.000000,90.000040,90.503133,93.478301,95.000000,95.878136
"Bahamas, The",0.000000,NaN,NaN,NaN,NaN,0.960031,1.746951,1.362954,2.335591,3.764558,...,31.540000,33.880000,43.000000,65.000000,71.748203,72.000000,76.920000,78.000000,80.000000,85.000000
Bosnia and Herzegovina,0.000000,NaN,NaN,NaN,NaN,NaN,0.015126,0.059426,0.143671,0.194374,...,34.660000,37.740000,42.750000,43.887687,45.064500,48.521314,49.917732,52.600000,60.260000,69.491152
Belarus,0.000000,NaN,NaN,NaN,0.000486,0.002921,0.029298,0.049021,0.073869,0.494881,...,23.000000,27.430000,31.800000,39.648896,46.910000,54.170000,59.020000,67.300000,71.113046,74.436445
Belize,0.000000,NaN,NaN,NaN,NaN,0.045397,0.882807,1.288582,2.091516,4.076741,...,26.300000,27.200000,28.200000,30.700000,31.000000,33.600000,38.700000,41.590000,44.575740,47.082626
Bermuda,0.000000,NaN,NaN,NaN,NaN,6.838163,16.202466,24.189257,32.103759,39.947589,...,82.300000,83.250000,84.210000,88.336000,91.299305,95.300000,96.800000,98.323610,98.000000,98.370000
Bolivia,0.000000,NaN,NaN,NaN,NaN,0.066808,0.196081,0.447839,0.626484,0.981815,...,12.500000,16.800000,22.400000,30.000000,35.340000,36.990000,34.600000,35.562271,39.697515,43.832276
Brazil,0.000000,0.003288,0.012946,0.025498,0.037673,0.105138,0.450789,0.786079,1.477875,2.038732,...,33.830000,39.220000,40.650000,45.690000,48.560000,51.040000,54.551002,58.327952,60.872540,67.470000
Barbados,0.000000,NaN,NaN,NaN,NaN,0.007752,0.389464,0.783429,1.970249,2.376247,...,61.400000,64.700000,65.100000,66.500000,71.200000,71.800000,75.160000,76.110000,79.549398,81.760778
Brunei Darussalam,0.000000,NaN,NaN,NaN,NaN,1.017080,3.303350,4.831058,6.284743,7.671041,...,46.000000,49.000000,53.000000,56.000000,60.273065,64.500000,68.770000,71.200000,90.000000,94.866692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Turkmenistan,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.045021,...,1.750000,1.950000,3.000000,5.000000,7.195800,9.600000,12.200000,14.996775,17.990324,21.250997
Latin America & the Caribbean (IDA & IBRD countries),0.000000,NaN,0.013664,0.029908,0.050161,0.111181,0.313310,0.613853,1.237917,2.062211,...,26.676976,31.275791,34.984453,39.712840,43.404497,46.433479,48.945662,54.713013,57.534390,62.289090
Timor-Leste,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.500000,2.000000,3.000000,4.000000,7.000000,11.000000,17.500000,23.000000,25.246250,27.492732
Middle East & North Africa (IDA & IBRD countries),0.000000,NaN,NaN,NaN,0.002880,0.013379,0.026328,0.075241,0.159506,0.417799,...,14.961699,17.612149,20.529004,22.797099,26.056522,29.594575,34.599776,38.904628,42.870442,49.816162
Tonga,0.000000,NaN,NaN,NaN,NaN,0.123231,0.163793,0.510866,0.765134,1.017967,...,8.110770,10.000000,16.000000,25.000000,30.000000,32.753961,35.954441,38.651272,39.950000,41.248728
South Asia (IDA & IBRD),0.000000,NaN,0.000109,0.000213,0.001078,0.022549,0.040940,0.060249,0.117486,0.227407,...,4.408935,5.149468,7.205784,9.398097,11.520860,13.756213,19.083276,23.203573,26.456796,30.187792
Sub-Saharan Africa (IDA & IBRD countries),0.000000,NaN,NaN,NaN,NaN,NaN,0.069921,0.131108,0.238312,0.366122,...,3.880493,4.598676,6.992579,8.382886,10.263361,12.323987,14.686524,18.067132,19.809935,22.118160
Trinidad and Tobago,0.000000,NaN,NaN,NaN,NaN,0.158150,0.393081,1.173175,2.724825,5.814251,...,34.800000,44.300000,48.500000,55.200000,59.516200,63.800000,65.100000,69.198471,73.296941,77.326053
Tunisia,0.000000,NaN,NaN,NaN,0.007380,0.011192,0.027615,0.043657,0.107941,1.602495,...,27.530000,34.070000,36.800000,39.100000,41.441600,43.800000,46.160000,46.500000,49.600000,55.500000
Turkey,0.000000,NaN,NaN,0.008458,0.049869,0.081691,0.192725,0.473695,0.698805,2.292118,...,34.370000,36.400000,39.820000,43.065710,45.130000,46.250000,51.040000,53.744979,58.347734,64.684618
Tuvalu,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.000000,20.000000,25.000000,30.000000,35.000000,37.000000,39.200000,42.700000,46.009152,49.318339
Tanzania,0.000000,NaN,NaN,NaN,NaN,NaN,0.001622,0.007900,0.009244,0.075131,...,1.900000,2.400000,2.900000,3.200000,3.950000,4.400000,7.000000,10.000000,13.000000,15.999999
Uganda,0.000000,NaN,NaN,NaN,NaN,0.002863,0.004626,0.010319,0.065289,0.105544,...,7.900000,9.780000,12.500000,13.013543,14.100000,15.500000,16.900000,17.834859,21.876170,23.706531
Ukraine,0.000000,NaN,NaN,0.000777,0.013641,0.043084,0.098580,0.198822,0.301076,0.405385,...,11.000000,17.900000,23.300000,28.708263,35.270000,40.954129,46.235975,48.884644,53.000000,57.115139
Upper middle income,0.000000,NaN,NaN,0.009298,0.021715,0.052887,0.123667,0.257539,0.605318,1.264552,...,23.166093,28.144281,33.479868,37.744311,42.386501,45.774477,48.642238,52.035933,55.349724,58.432434
Uruguay,0.000000,NaN,NaN,NaN,0.062474,0.310129,1.847472,3.363240,6.987069,9.972765,...,39.300000,41.800000,46.400000,51.404661,54.453769,57.690000,61.460000,64.600000,66.400000,68.279663
United States,0.784729,1.163194,1.724203,2.271673,4.862781,9.237088,16.419353,21.616401,30.093197,35.848724,...,74.000000,71.000000,71.690000,69.729461,74.700000,71.400000,73.000000,74.554202,75.232643,75.232643
Uzbekistan,0.000000,NaN,NaN,NaN,NaN,0.001527,0.004285,0.010537,0.020754,0.030688,...,9.080115,11.900000,15.900000,18.600000,23.600000,26.800000,35.500000,42.800000,46.791287,52.305101
St. Vincent and the Grenadines,0.000000,NaN,NaN,NaN,NaN,0.128635,0.483248,0.926372,1.853998,2.782002,...,21.000000,31.000000,33.700000,36.700000,40.000000,43.500000,47.400000,51.770000,55.574619,65.560000
"Venezuela, RB",0.000000,NaN,0.012082,0.041587,0.055487,0.122215,0.248261,0.390959,1.383990,2.839826,...,25.880000,32.700000,37.370000,40.220000,49.050083,54.900000,57.000000,60.000000,60.000000,64.313364
British Virgin Islands,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,36.000000,37.000000,37.400000,37.600000,NaN,NaN,NaN,NaN,NaN
Virgin Islands (U.S.),0.000000,NaN,NaN,NaN,0.940645,2.801958,4.647186,6.948369,9.245220,11.074606,...,27.361777,27.396510,31.220000,35.600000,40.547900,45.300000,50.070000,54.839137,59.608316,64.377494
Vietnam,0.000000,NaN,NaN,NaN,NaN,NaN,0.000135,0.003982,0.013079,0.128927,...,23.920000,26.550000,30.650000,35.070000,36.800000,38.500000,41.000000,43.500000,46.500000,49.569097
Vanuatu,0.000000,NaN,NaN,NaN,NaN,NaN,0.056846,0.139506,0.274186,0.538300,...,7.269120,7.500000,8.000000,9.200000,10.598000,11.300000,18.800000,22.351405,24.000000,25.719788
World,0.049343,NaN,NaN,0.251847,0.447031,0.777442,1.325952,2.042439,3.141586,4.638776,...,22.950561,25.356345,28.733604,31.124506,34.193432,36.724639,39.771953,42.962959,45.673290,48.565131
Samoa,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.174572,0.230359,0.285308,...,5.031615,6.000000,7.000000,11.000000,12.922490,15.300000,21.200000,25.407010,29.411730,33.610939
"Yemen, Rep.",0.000000,NaN,NaN,NaN,NaN,NaN,0.000621,0.015025,0.023323,0.056629,...,6.890000,9.960000,12.350000,14.905000,17.446500,20.000000,22.550000,24.085409,24.579208,26.718355
South Africa,0.000000,0.013284,0.038869,0.113747,0.246906,0.676740,0.841883,1.632094,2.906221,4.116250,...,8.430000,10.000000,24.000000,33.970000,41.000000,46.500000,49.000000,51.919116,54.000000,56.167394
Zambia,0.000000,NaN,NaN,NaN,0.006776,0.008784,0.009069,0.009330,0.030226,0.147053,...,5.550000,6.310000,10.000000,11.500000,13.468200,15.400000,19.000000,21.000000,25.506579,27.852579
Zimbabwe,0.000000,NaN,NaN,NaN,0.001739,0.007684,0.016790,0.033080,0.081648,0.161676,...,3.500000,4.000000,6.400000,8.400000,12.000000,15.500000,16.364740,22.742818,23.119989,27.055488

In [29]:
internet_users_v2.values

array([[0.00000000e+00,            nan,            nan, ...,
        8.86612269e+01, 9.35424539e+01, 9.71700000e+01],
       [0.00000000e+00,            nan,            nan, ...,
        8.26000000e+00, 1.05957264e+01, 1.14476881e+01],
       [0.00000000e+00,            nan,            nan, ...,
        1.24000000e+01, 1.30000000e+01, 1.43390794e+01],
       ...,
       [0.00000000e+00, 1.32835910e-02, 3.88691060e-02, ...,
        5.19191157e+01, 5.40000000e+01, 5.61673945e+01],
       [0.00000000e+00,            nan,            nan, ...,
        2.10000000e+01, 2.55065789e+01, 2.78525791e+01],
       [0.00000000e+00,            nan,            nan, ...,
        2.27428181e+01, 2.31199890e+01, 2.70554877e+01]])

Aqui pretendo verificar se um NAN está envolto de dois valores existentes e torná-lo a média entre estes dois valores

In [36]:
for value_set in range(len(internet_users_v2.values)):
    for value in range(value_set):
        if internet_users_v2.iloc[value_set, value].isna:
            print("NAN")

AttributeError: 'numpy.float64' object has no attribute 'isna'

In [ ]:
y = internet_users_v1.mean()
x = y.index

plt.figure(figsize=(30,10))
plt.plot(x,y)

## Conclusão

Responda à pergunta, argumento da melhor forma possível com base nos dados